/* 0 */ {COMM_CTYPE_DEFAULT,	{13, 0}, { 14, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 1 */ {COMM_CTYPE_DEFAULT,	{13, 0}, { 14, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 2 */ {COMM_CTYPE_DEFAULT,	{13, 0}, { 14, 0 }, 4, NUM_TOKEN, }, /** (Y2--->X2)null--> null **/
/* 3 */ {COMM_CTYPE_DEFAULT,	{13, 0}, { 14, 0 }, 4, NUM_TOKEN, }, /** (Y3--->X3)null--> null **/
/* 4 */ {COMM_CTYPE_DEFAULT,	{14, 0}, { 15, 0 }, 4, NUM_TOKEN, }, /** (Y--->I)null--> null **/
/* 5 */ {COMM_CTYPE_DEFAULT,	{2, 0}, { 3, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 6 */ {COMM_CTYPE_DEFAULT,	{2, 0}, { 3, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 7 */ {COMM_CTYPE_DEFAULT,	{2, 0}, { 3, 0 }, 4, NUM_TOKEN, }, /** (Y2--->X2)null--> null **/
/* 8 */ {COMM_CTYPE_DEFAULT,	{2, 0}, { 3, 0 }, 4, NUM_TOKEN, }, /** (Y3--->X3)null--> null **/
/* 9 */ {COMM_CTYPE_DEFAULT,	{3, 0}, { 4, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 10 */ {COMM_CTYPE_DEFAULT,	{3, 0}, { 4, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 11 */ {COMM_CTYPE_DEFAULT,	{4, 0}, { 5, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 12 */ {COMM_CTYPE_DEFAULT,	{4, 0}, { 5, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 13 */ {COMM_CTYPE_DEFAULT,	{4, 0}, { 5, 0 }, 4, NUM_TOKEN, }, /** (Y2--->X2)null--> null **/
/* 14 */ {COMM_CTYPE_DEFAULT,	{4, 0}, { 5, 0 }, 4, NUM_TOKEN, }, /** (Y3--->X3)null--> null **/
/* 15 */ {COMM_CTYPE_DEFAULT,	{5, 0}, { 6, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 16 */ {COMM_CTYPE_DEFAULT,	{5, 0}, { 6, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 17 */ {COMM_CTYPE_DEFAULT,	{5, 0}, { 6, 0 }, 4, NUM_TOKEN, }, /** (Y2--->X2)null--> null **/
/* 18 */ {COMM_CTYPE_DEFAULT,	{5, 0}, { 6, 0 }, 4, NUM_TOKEN, }, /** (Y3--->X3)null--> null **/
/* 19 */ {COMM_CTYPE_DEFAULT,	{8, 0}, { 9, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 20 */ {COMM_CTYPE_DEFAULT,	{8, 0}, { 9, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 21 */ {COMM_CTYPE_DEFAULT,	{8, 0}, { 9, 0 }, 4, NUM_TOKEN, }, /** (Y2--->X2)null--> null **/
/* 22 */ {COMM_CTYPE_DEFAULT,	{8, 0}, { 9, 0 }, 4, NUM_TOKEN, }, /** (Y3--->X3)null--> null **/
/* 23 */ {COMM_CTYPE_DEFAULT,	{9, 0}, { 10, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 24 */ {COMM_CTYPE_DEFAULT,	{9, 0}, { 10, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 25 */ {COMM_CTYPE_DEFAULT,	{10, 0}, { 11, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 26 */ {COMM_CTYPE_DEFAULT,	{10, 0}, { 11, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 27 */ {COMM_CTYPE_DEFAULT,	{10, 0}, { 11, 0 }, 4, NUM_TOKEN, }, /** (Y2--->X2)null--> null **/
/* 28 */ {COMM_CTYPE_DEFAULT,	{10, 0}, { 11, 0 }, 4, NUM_TOKEN, }, /** (Y3--->X3)null--> null **/
/* 29 */ {COMM_CTYPE_DEFAULT,	{11, 0}, { 12, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 30 */ {COMM_CTYPE_DEFAULT,	{11, 0}, { 12, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 31 */ {COMM_CTYPE_DEFAULT,	{11, 0}, { 12, 0 }, 4, NUM_TOKEN, }, /** (Y2--->X2)null--> null **/
/* 32 */ {COMM_CTYPE_DEFAULT,	{11, 0}, { 12, 0 }, 4, NUM_TOKEN, }, /** (Y3--->X3)null--> null **/
/* 33 */ {COMM_CTYPE_DEFAULT,	{15, 0}, { 16, 0 }, 4, NUM_TOKEN, }, /** (O--->B)null--> null **/
/* 34 */ {COMM_CTYPE_DEFAULT,	{0, 0}, { 1, 0 }, 4, NUM_TOKEN, }, /** (V--->ROW)null--> null **/
/* 35 */ {COMM_CTYPE_DEFAULT,	{0, 0}, { 15, 0 }, 4, NUM_TOKEN, }, /** (Signed--->SIGNED)null--> null **/
/* 36 */ {COMM_CTYPE_DEFAULT,	{6, 0}, { 7, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 37 */ {COMM_CTYPE_DEFAULT,	{6, 0}, { 7, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 38 */ {COMM_CTYPE_DEFAULT,	{6, 0}, { 7, 0 }, 4, NUM_TOKEN, }, /** (Y2--->X2)null--> null **/
/* 39 */ {COMM_CTYPE_DEFAULT,	{6, 0}, { 7, 0 }, 4, NUM_TOKEN, }, /** (Y3--->X3)null--> null **/
/* 40 */ {COMM_CTYPE_DEFAULT,	{12, 0}, { 13, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 41 */ {COMM_CTYPE_DEFAULT,	{12, 0}, { 13, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 42 */ {COMM_CTYPE_DEFAULT,	{12, 0}, { 13, 0 }, 4, NUM_TOKEN, }, /** (Y2--->X2)null--> null **/
/* 43 */ {COMM_CTYPE_DEFAULT,	{12, 0}, { 13, 0 }, 4, NUM_TOKEN, }, /** (Y3--->X3)null--> null **/
/* 44 */ {COMM_CTYPE_DEFAULT,	{1, 0}, { 2, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 45 */ {COMM_CTYPE_DEFAULT,	{1, 0}, { 2, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/
/* 46 */ {COMM_CTYPE_DEFAULT,	{7, 0}, { 8, 0 }, 4, NUM_TOKEN, }, /** (Y0--->X0)null--> null **/
/* 47 */ {COMM_CTYPE_DEFAULT,	{7, 0}, { 8, 0 }, 4, NUM_TOKEN, }, /** (Y1--->X1)null--> null **/

